research-project/
    asyncio_arch/
        asyncio_server.py
        asyncio_client.py
        thread_asyncio_server.py
        class_thread_server.py
    compression_test/
        compression_test.py
        recorded_audio_stream.py
        test_audio_compression.py
    config/
    	config.py
    flask_arch/
    	client.py
    	server.py
    	stream.py
    google examples/
        google_example_record_for_stream.py
        google_example_stream.py
    opus/
    	opus_client.py
    	opus_server.py
        opus_test.py
    resources/
        apikey.py
    versions/
        client.py
        googleSpeechAPI.py
        server.py
        serverv2.py
        Stream_API_Google.py
        stream_speech_api.py
    